# Generated by Django 4.1.7 on 2023-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
