# Generated by Django 4.1.7 on 2023-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_alter_book_category_delete_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='product_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
