# Generated by Django 4.1.7 on 2023-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='product_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
